# Jekyll configuration for GitHub Pages
title: Ergodic Insurance Limits
description: A framework for optimizing insurance limits using ergodic theory
theme: jekyll-theme-cayman
baseurl: "/Ergodic-Insurance-Limits"
url: "https://alexfiliakov.github.io"
source: .
destination: _site

# Markdown configuration
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# Include/Exclude
include:
  - docs
  - _layouts
  - _includes
exclude:
  - ergodic_insurance/docs/_build
  - "*.pyc"
  - __pycache__
  - node_modules
  - cache
  - htmlcov
  - checkpoints
  - test_trajectory_storage
  - simone/node_modules

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
