# Jekyll configuration for GitHub Pages
title: Ergodic Insurance Limits
description: A framework for optimizing insurance limits using ergodic theory
theme: jekyll-theme-cayman
repository: AlexFiliakov/Ergodic-Insurance-Limits
baseurl: "/Ergodic-Insurance-Limits"
url: "https://alexfiliakov.github.io"
source: .
destination: _site

# Markdown configuration
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Defaults
defaults:
  - scope:
      path: "docs/tutorials"
    values:
      layout: "default"
      permalink: /tutorials/:basename/
  - scope:
      path: "docs/user_guide"
    values:
      layout: "default"
      permalink: /user_guide/:basename/
  - scope:
      path: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# Include/Exclude
include:
  - index.html
  - theory
  - docs
  - docs/tutorials
  - docs/user_guide
  - tutorials
  - api
  - _layouts
  - _includes
exclude:
  - vendor/
  - ergodic_insurance/
  - simone/
  - "*.pyc"
  - __pycache__/
  - node_modules/
  - cache/
  - htmlcov/
  - checkpoints/
  - test_trajectory_storage/
  - "*.pkl"
  - "*.parquet"
  - Gemfile
  - LICENSE
  - "*.md~"
  - ".git/"
  - ".github/"
  - "*.log"
  - results/figures/
  - reports/
  - issues/
  - mypy.ini
  - pytest.ini
  - setup.py
  - pyproject.toml
  - uv.lock
  - main.py
  - "test_*.py"
  - "*.ipynb"
  - "*.json"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
